[package]
name = "pfile"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
